# Computer Vision Using OpenCV
## Install opencv-python 4.5

In [2]:
pip install opencv-python

In [1]:
import cv2

In [2]:
img = cv2.imread('girl-original.jpeg')

In [3]:
img

array([[[175, 174, 164],
        [176, 175, 165],
        [177, 176, 166],
        ...,
        [188, 193, 191],
        [188, 193, 191],
        [188, 193, 191]],

       [[175, 174, 164],
        [175, 174, 164],
        [176, 175, 165],
        ...,
        [188, 193, 191],
        [188, 193, 191],
        [188, 193, 191]],

       [[174, 174, 162],
        [175, 175, 163],
        [176, 176, 164],
        ...,
        [188, 194, 189],
        [188, 194, 189],
        [188, 194, 189]],

       ...,

       [[138, 155, 188],
        [136, 153, 186],
        [136, 152, 188],
        ...,
        [ 50,  72, 113],
        [ 53,  73, 114],
        [ 54,  74, 115]],

       [[138, 154, 190],
        [136, 152, 188],
        [136, 152, 188],
        ...,
        [ 56,  75, 118],
        [ 59,  76, 119],
        [ 59,  76, 119]],

       [[139, 155, 191],
        [137, 153, 189],
        [136, 152, 188],
        ...,
        [ 59,  78, 121],
        [ 62,  79, 122],
        [ 63,  80, 123]]

## Lets look at what we are working with and the shape!

In [5]:
print(type(img))
print(img.shape)

<class 'numpy.ndarray'>
(1500, 1000, 3)


In [6]:
cv2.imshow("Original", img)
cv2.waitKey(0)

-1

In [7]:
small = cv2.resize(img, (0,0), fx=0.5, fy=0.5)

In [8]:
cv2.imshow("Small!", small)
cv2.waitKey(0)

-1

In [9]:
small.shape

(750, 500, 3)

## Take a look at the first pixel! OpenCV2 - BGR

In [10]:
small[0,0]

array([175, 174, 164], dtype=uint8)

## Lets give it a new value

In [19]:
small[0,0] = (255,255,255)

In [20]:
small[0,0]

array([255, 255, 255], dtype=uint8)

In [21]:
cv2.imshow("Small!", small)
cv2.waitKey(0)

-1

## Lets change the first 100 rows and 10 colums to red

In [22]:
small[0:100,0:10] = (0,0,255)

In [23]:
cv2.imshow("Small!", small)
cv2.waitKey(0)

-1

## Grayscale Image

In [11]:
gray = cv2.cvtColor(small, cv2.COLOR_BGR2GRAY)
gray.shape

(750, 500)

In [35]:
cv2.imshow("Gray", gray)
cv2.waitKey(0)

-1

## Save Image

In [37]:
cv2.imwrite("Gray.png", gray) 

True