In [1]:
import cv2

In [2]:
img = cv2.imread('sea.jpeg')

In [3]:
type(img)

numpy.ndarray

In [10]:
cv2.imshow("Brrrrrr", img)
cv2.waitKey(0)

-1

In [ ]:
img = cv2.resize(img, (0,0), fx=.5, fy=.5)

## Lets draw square like you see in object detection tutorials!
x1,y1 ------<br>
| &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |<br>
| &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |<br>
| &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |<br>
-------------x2,y2

In [5]:
cv2.rectangle(img, (430, 216), (524, 285), (0,255,0), 5)

array([[[151, 138, 124],
        [151, 138, 124],
        [151, 138, 124],
        ...,
        [161, 152, 142],
        [160, 151, 141],
        [157, 148, 138]],

       [[150, 137, 123],
        [150, 137, 123],
        [150, 137, 123],
        ...,
        [161, 152, 139],
        [160, 151, 138],
        [157, 148, 135]],

       [[149, 136, 122],
        [149, 136, 122],
        [149, 136, 122],
        ...,
        [159, 150, 137],
        [158, 149, 136],
        [157, 148, 135]],

       ...,

       [[150, 146, 145],
        [150, 146, 145],
        [150, 146, 145],
        ...,
        [167, 168, 166],
        [167, 168, 166],
        [166, 167, 165]],

       [[150, 146, 145],
        [152, 148, 147],
        [152, 148, 147],
        ...,
        [168, 169, 167],
        [166, 167, 165],
        [168, 169, 167]],

       [[149, 145, 144],
        [151, 147, 146],
        [151, 147, 146],
        ...,
        [168, 169, 167],
        [166, 167, 165],
        [164, 165, 163]]

In [6]:
cv2.rectangle(img, (973, 259), (1070, 326), (255,0,255), 5)

array([[[151, 138, 124],
        [151, 138, 124],
        [151, 138, 124],
        ...,
        [161, 152, 142],
        [160, 151, 141],
        [157, 148, 138]],

       [[150, 137, 123],
        [150, 137, 123],
        [150, 137, 123],
        ...,
        [161, 152, 139],
        [160, 151, 138],
        [157, 148, 135]],

       [[149, 136, 122],
        [149, 136, 122],
        [149, 136, 122],
        ...,
        [159, 150, 137],
        [158, 149, 136],
        [157, 148, 135]],

       ...,

       [[150, 146, 145],
        [150, 146, 145],
        [150, 146, 145],
        ...,
        [167, 168, 166],
        [167, 168, 166],
        [166, 167, 165]],

       [[150, 146, 145],
        [152, 148, 147],
        [152, 148, 147],
        ...,
        [168, 169, 167],
        [166, 167, 165],
        [168, 169, 167]],

       [[149, 145, 144],
        [151, 147, 146],
        [151, 147, 146],
        ...,
        [168, 169, 167],
        [166, 167, 165],
        [164, 165, 163]]

In [7]:
cv2.putText(img, 'Penguin!', (432,320), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,0), 2)

array([[[151, 138, 124],
        [151, 138, 124],
        [151, 138, 124],
        ...,
        [161, 152, 142],
        [160, 151, 141],
        [157, 148, 138]],

       [[150, 137, 123],
        [150, 137, 123],
        [150, 137, 123],
        ...,
        [161, 152, 139],
        [160, 151, 138],
        [157, 148, 135]],

       [[149, 136, 122],
        [149, 136, 122],
        [149, 136, 122],
        ...,
        [159, 150, 137],
        [158, 149, 136],
        [157, 148, 135]],

       ...,

       [[150, 146, 145],
        [150, 146, 145],
        [150, 146, 145],
        ...,
        [167, 168, 166],
        [167, 168, 166],
        [166, 167, 165]],

       [[150, 146, 145],
        [152, 148, 147],
        [152, 148, 147],
        ...,
        [168, 169, 167],
        [166, 167, 165],
        [168, 169, 167]],

       [[149, 145, 144],
        [151, 147, 146],
        [151, 147, 146],
        ...,
        [168, 169, 167],
        [166, 167, 165],
        [164, 165, 163]]

In [8]:
cv2.circle(img, (252,252), 50, (100,100,5), 5)

array([[[151, 138, 124],
        [151, 138, 124],
        [151, 138, 124],
        ...,
        [161, 152, 142],
        [160, 151, 141],
        [157, 148, 138]],

       [[150, 137, 123],
        [150, 137, 123],
        [150, 137, 123],
        ...,
        [161, 152, 139],
        [160, 151, 138],
        [157, 148, 135]],

       [[149, 136, 122],
        [149, 136, 122],
        [149, 136, 122],
        ...,
        [159, 150, 137],
        [158, 149, 136],
        [157, 148, 135]],

       ...,

       [[150, 146, 145],
        [150, 146, 145],
        [150, 146, 145],
        ...,
        [167, 168, 166],
        [167, 168, 166],
        [166, 167, 165]],

       [[150, 146, 145],
        [152, 148, 147],
        [152, 148, 147],
        ...,
        [168, 169, 167],
        [166, 167, 165],
        [168, 169, 167]],

       [[149, 145, 144],
        [151, 147, 146],
        [151, 147, 146],
        ...,
        [168, 169, 167],
        [166, 167, 165],
        [164, 165, 163]]

In [9]:
cv2.imwrite('smallfinal.png',img)

True